<?php $title = 'Mon blog - Biographie'; ?>

<div class="container bio">
    <aside id="photoBio"><img src="public/imgs/busteH.png" alt="photo de l'auteur"></aside>
    <p>  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur porro excepturi cumque facere doloribus corporis soluta officiis quae. Optio magni, amet at qui ipsum voluptate? Consequatur deleniti sapiente rerum ducimus!
    </p>
    <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum facilis, suscipit aspernatur expedita aperiam pariatur, fugiat ab et eaque placeat reiciendis, quis, est mollitia quam tenetur ut officiis optio corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis nulla, non ipsum, doloribus minima a similique in exercitationem corporis deserunt eaque obcaecati quae explicabo ducimus blanditiis consectetur fuga. Modi, corporis! ipsum dolor sit amet, consectetur adipisicing elit. Natus consequuntur, libero error ipsum tempora voluptatum quo dolorum hic esse ut reprehenderit magnam, eveniet dolores unde, odit neque excepturi autem explicabo.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe in fuga dicta voluptas! Odio, cumque. Excepturi similique reprehenderit, dicta blanditiis iure nam nesciunt eaque nobis dignissimos corporis praesentium error doloribus. ipsum dolor sit amet, consectetur adipisicing elit. Soluta optio, vitae, alias asperiores dicta reiciendis ipsam eaque voluptatum hic labore illo est esse iste ullam illum minima dignissimos. Quos, voluptatem.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur porro excepturi cumque facere doloribus corporis soluta officiis quae. Optio magni, amet at qui ipsum voluptate? Consequatur deleniti sapiente rerum ducimus!
    </p>
    <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum facilis, suscipit aspernatur expedita aperiam pariatur, fugiat ab et eaque placeat reiciendis, quis, est mollitia quam tenetur ut officiis optio corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis nulla, non ipsum, doloribus minima a similique in exercitationem corporis deserunt eaque obcaecati quae explicabo ducimus blanditiis consectetur fuga. Modi, corporis! ipsum dolor sit amet, consectetur adipisicing elit. Natus consequuntur, libero error ipsum tempora voluptatum quo dolorum hic esse ut reprehenderit magnam, eveniet dolores unde, odit neque excepturi autem explicabo.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe in fuga dicta voluptas! Odio, cumque. Excepturi similique reprehenderit, dicta blanditiis iure nam nesciunt eaque nobis dignissimos corporis praesentium error doloribus. ipsum dolor sit amet, consectetur adipisicing elit. Soluta optio, vitae, alias asperiores dicta reiciendis ipsam eaque voluptatum hic labore illo est esse iste ullam illum minima dignissimos. Quos, voluptatem.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur porro excepturi cumque facere doloribus corporis soluta officiis quae. Optio magni, amet at qui ipsum voluptate? Consequatur deleniti sapiente rerum ducimus!
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum facilis, suscipit aspernatur expedita aperiam pariatur, fugiat ab et eaque placeat reiciendis, quis, est mollitia quam tenetur ut officiis optio corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis nulla, non ipsum, doloribus minima a similique in exercitationem corporis deserunt eaque obcaecati quae explicabo ducimus blanditiis consectetur fuga. Modi, corporis! ipsum dolor sit amet, consectetur adipisicing elit. Natus consequuntur, libero error ipsum tempora voluptatum quo dolorum hic esse ut reprehenderit magnam, eveniet dolores unde, odit neque excepturi autem explicabo.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe in fuga dicta voluptas! Odio, cumque. Excepturi similique reprehenderit, dicta blanditiis iure nam nesciunt eaque nobis dignissimos corporis praesentium error doloribus. ipsum dolor sit amet, consectetur adipisicing elit. Soluta optio, vitae, alias asperiores dicta reiciendis ipsam eaque voluptatum hic labore illo est esse iste ullam illum minima dignissimos. Quos, voluptatem.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur porro excepturi cumque facere doloribus corporis soluta officiis quae. Optio magni, amet at qui ipsum voluptate? Consequatur deleniti sapiente rerum ducimus!
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum facilis, suscipit aspernatur expedita aperiam pariatur, fugiat ab et eaque placeat reiciendis, quis, est mollitia quam tenetur ut officiis optio corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis nulla, non ipsum, doloribus minima a similique in exercitationem corporis deserunt eaque obcaecati quae explicabo ducimus blanditiis consectetur fuga. Modi, corporis! ipsum dolor sit amet, consectetur adipisicing elit. Natus consequuntur, libero error ipsum tempora voluptatum quo dolorum hic esse ut reprehenderit magnam, eveniet dolores unde, odit neque excepturi autem explicabo.
    </p>
    <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe in fuga dicta voluptas! Odio, cumque. Excepturi similique reprehenderit, dicta blanditiis iure nam nesciunt eaque nobis dignissimos corporis praesentium error doloribus. ipsum dolor sit amet, consectetur adipisicing elit. Soluta optio, vitae, alias asperiores dicta reiciendis ipsam eaque voluptatum hic labore illo est esse iste ullam illum minima dignissimos. Quos, voluptatem.
    </p>
</div>




